### ISSUE TITLE
训练以及测试模型

### ISSUE THREAD

**Issue by excllent123** [opteroncx/MDDM#1]
model 的代码和论文对不上呀，楼主是有改进吗

另外 训练部分代码以及对应的模型会开源吗、谢谢

**Comment by opteroncx** [comment]
model已上传。前几天实验室网有问题没更新上去

**Comment by opteroncx** [comment]
论文里的图示是以比赛时为准的，其实当时做了很多版本，这里的是改进精简后的版本
